#!/usr/bin/env python
#-*- coding:utf-8 -*-

import ansible.runner
import json
import re
import copy
import sys
import requests

SCRIPT=sys.argv[1]
IPFILE=sys.argv[2]
PRIKEY=''
LOGPATH=''

def multi_run():
    runner = ansible.runner.Runner(
            host_list=IPFILE,
            module_name="script",
            module_args=SCRIPT,
            pattern="",
            forks=50,
            become="True",
            timeout=3
    )
    data = runner.run()
    #data = runner.run_async(time_limit)
    return(data)



def write_log(data):
    if LOGPATH:
        with open('LOGPATH', 'a') as f:
            f.write(data)



if __name__ == '__main__':
    if len(sys.argv) == 3:
        data = multi_run()
        print data
        #ret = {}
        #for k,v in data['contacted'].items():
        #    ret[k] = v['stdout'].split(',')
        #    print(json.dumps(ret,indent=1).replace("\\r\\n", "\n").replace("\\t", "\t"))
    else:
        print "Usage: ./check.py command.sh ip.list"
        print len(sys.argv)
        sys.exit(1)

